### PR TITLE
Dfhussey fox

### PR DESCRIPTION
**Pull request by friedmud**

### CODE REVIEW

**Comment by friedmud** [comment]
Just a heads up: there are more changes that we would propose for your application.  However, since you haven't merged this PR yet we're not going to propose another one.

Let us know if you're still actively developing your application and if you would still like to receive updates from us.

Thanks!

**Comment by dfhussey** [comment]
Derek, 
I will work on it after I get settled into my CASL role, I was thinking that the training may be best before putting a lot of time.  When is the next session?
Dennis

**Comment by friedmud** [comment]
Sounds good Dennis... in the mean time you should probably Merge our Pull Requests (just press the big green button below) to keep your application up to date.

I think the next training will be in June - stay tuned for an announcement soon.

**Comment by dfhussey** [comment]
Done, let me know if you need anything else.
--Dennis

**Pull request merged**
